name: weather_icons_flutter
description: Weather icons wrapper
version: 1.0.1
author: Dan Balarin <dan.balarin@gmail.com>
homepage: https://github.com/Kenny11CZ/weather_icons_flutter


dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
  - family: WeatherIcons
    fonts:
      - asset: assets/weathericons-regular.ttf
        weight: 400
